import Head from 'next/head'

// fix this import
// import Inter from 'inter-ui'
// import Inter from 'inter-ui/inter.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className='container mx-auto'>
          Hello World
        </div>
      </main>
    </>
  )
}
